// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID           uuid.UUID        `json:"id"`
	Type         string           `json:"type"`
	Status       string           `json:"status"`
	Payload      []byte           `json:"payload"`
	Result       []byte           `json:"result"`
	ErrorMessage pgtype.Text      `json:"error_message"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
