// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID           uuid.UUID  `json:"id"`
	Type         string     `json:"type"`
	Status       string     `json:"status"`
	Payload      []byte     `json:"payload"`
	Result       []byte     `json:"result"`
	ErrorMessage *string    `json:"error_message"`
	RetryCount   int32      `json:"retry_count"`
	MaxRetries   int32      `json:"max_retries"`
	NextRetryAt  *time.Time `json:"next_retry_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
