// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetTask(ctx context.Context, id uuid.UUID) (Task, error)
	// What Decides Placeholder Number(like $1,$2)? POSITION inside the query.
	IncrementRetry(ctx context.Context, id uuid.UUID) error
	MoveToFailed(ctx context.Context, id uuid.UUID) error
	ScheduleRetry(ctx context.Context, arg ScheduleRetryParams) (int64, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
}

var _ Querier = (*Queries)(nil)
