// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    type,
    status,
    payload
) VALUES (
    $1, $2, $3
)
RETURNING id, type, status, payload, result, error_message, created_at, updated_at
`

type CreateTaskParams struct {
	Type    string `json:"type"`
	Status  string `json:"status"`
	Payload []byte `json:"payload"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Type, arg.Status, arg.Payload)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, type, status, payload, result, error_message, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
