// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tasks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    type,
    status,
    payload
) VALUES (
    $1, $2, $3
)
RETURNING id, type, status, payload, result, error_message, retry_count, max_retries, next_retry_at, created_at, updated_at
`

type CreateTaskParams struct {
	Type    string `json:"type"`
	Status  string `json:"status"`
	Payload []byte `json:"payload"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask, arg.Type, arg.Status, arg.Payload)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, type, status, payload, result, error_message, retry_count, max_retries, next_retry_at, created_at, updated_at FROM tasks
WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.Payload,
		&i.Result,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.MaxRetries,
		&i.NextRetryAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRetry = `-- name: IncrementRetry :exec

UPDATE tasks
SET retry_count = retry_count + 1, updated_at = NOW()
WHERE id = $1
`

// What Decides Placeholder Number(like $1,$2)? POSITION inside the query.
func (q *Queries) IncrementRetry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementRetry, id)
	return err
}

const moveToFailed = `-- name: MoveToFailed :exec
UPDATE tasks
SET status = 'failed',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) MoveToFailed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, moveToFailed, id)
	return err
}

const scheduleRetry = `-- name: ScheduleRetry :execrows
UPDATE tasks
SET retry_count = retry_count + 1,
    next_retry_at = $2,
    updated_at = NOW()
WHERE id = $1 AND retry_count < max_retries
`

type ScheduleRetryParams struct {
	ID          uuid.UUID  `json:"id"`
	NextRetryAt *time.Time `json:"next_retry_at"`
}

func (q *Queries) ScheduleRetry(ctx context.Context, arg ScheduleRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleRetry, arg.ID, arg.NextRetryAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
